"""
ParkWise AI - Data Processing Pipeline

This module handles the complete data processing pipeline:
1. CSV Loading & Cleaning
2. DBSCAN Clustering for hotspot detection
3. Zone naming from location data
4. Impact Score calculation
5. Density & Impact ranking
6. Recommendation generation
7. Database persistence
"""

import os
import re
import json
import numpy as np
import pandas as pd
from collections import Counter

from database import engine, init_db, SessionLocal
from models import Hotspot, HotspotDetail, Recommendation
from recommendations import generate_zone_recommendation, classify_zone


# ============================================================
# Vehicle type standardization map
# ============================================================
VEHICLE_TYPE_MAP = {
    "CAR": "CAR",
    "MAXI-CAB": "MAXI CAB",
    "MAXI CAB": "MAXI CAB",
    "MAXICAB": "MAXI CAB",
    "TAXI": "MAXI CAB",
    "SCOOTER": "BIKE",
    "MOTOR CYCLE": "BIKE",
    "MOTORCYCLE": "BIKE",
    "MOPED": "BIKE",
    "BIKE": "BIKE",
    "PASSENGER AUTO": "AUTO",
    "AUTO": "AUTO",
    "GOODS AUTO": "AUTO",
    "AUTO RICKSHAW": "AUTO",
    "BUS": "BUS",
    "TRUCK": "TRUCK",
    "LORRY": "TRUCK",
    "HGV": "TRUCK",
    "LGV": "TRUCK",
    "TANKER": "TRUCK",
    "VAN": "CAR",
    "OTHERS": "OTHERS",
    "TRACTOR": "TRUCK",
    "AMBULANCE": "OTHERS",
    "JEEP": "CAR",
    "MINIBUS": "BUS",
}

# Vehicle impact weights for scoring
VEHICLE_WEIGHTS = {
    "BIKE": 1,
    "AUTO": 2,
    "CAR": 3,
    "MAXI CAB": 4,
    "BUS": 5,
    "TRUCK": 5,
    "OTHERS": 2,
}


def load_and_clean_data(csv_path: str) -> pd.DataFrame:
    """
    Step 1: Load CSV and clean the data.
    
    - Remove rows with null lat/lon
    - Remove duplicate records
    - Standardize vehicle types
    - Parse datetime fields
    """
    print("[1/6] Loading dataset...")
    df = pd.read_csv(csv_path, low_memory=False)
    print(f"  Loaded {len(df)} records")

    # Remove null coordinates
    initial_count = len(df)
    df = df.dropna(subset=["latitude", "longitude"])
    print(f"  Removed {initial_count - len(df)} rows with null coordinates")

    # Remove duplicates
    dup_count = df.duplicated(subset=["latitude", "longitude", "vehicle_number", "created_datetime"]).sum()
    df = df.drop_duplicates(subset=["latitude", "longitude", "vehicle_number", "created_datetime"])
    print(f"  Removed {dup_count} duplicate records")

    # Standardize vehicle types
    df["vehicle_type"] = df["vehicle_type"].fillna("OTHERS")
    df["vehicle_type_clean"] = df["vehicle_type"].str.upper().str.strip().map(
        lambda x: VEHICLE_TYPE_MAP.get(x, "OTHERS")
    )

    # Parse datetimes
    df["created_datetime"] = pd.to_datetime(df["created_datetime"], errors="coerce", utc=True)
    df["closed_datetime"] = pd.to_datetime(df["closed_datetime"], errors="coerce", utc=True)

    # Extract time features
    df["hour"] = df["created_datetime"].dt.hour
    df["day_of_week"] = df["created_datetime"].dt.dayofweek  # 0=Monday
    df["month"] = df["created_datetime"].dt.month

    # Compute resolution time in hours
    df["resolution_hours"] = (
        (df["closed_datetime"] - df["created_datetime"]).dt.total_seconds() / 3600
    )
    # Clamp negative and extreme values
    df["resolution_hours"] = df["resolution_hours"].clip(lower=0, upper=720)  # max 30 days

    # Clean location
    df["location"] = df["location"].fillna("")
    df["junction_name"] = df["junction_name"].fillna("No Junction")

    # Flag junction violations
    df["is_junction"] = df["junction_name"].apply(
        lambda x: 0 if x == "No Junction" else 1
    )

    # Clean police station
    df["police_station"] = df["police_station"].fillna("Unknown")

    print(f"  Final dataset: {len(df)} records")
    return df


def load_cluster_labels(df: pd.DataFrame, json_path: str) -> pd.DataFrame:
    """
    Step 2: Load pre-computed DBSCAN cluster labels from a JSON file.
    
    The JSON file is generated by running cluster.py externally on a
    machine with enough resources.  It contains a list of integer labels
    (one per cleaned row) and some metadata for validation.
    
    If clustering was run on a *subset* of the dataset (e.g. first 50%
    due to RAM limits), the DataFrame is automatically truncated to
    match the label count.
    
    Expected JSON structure:
        {
            "metadata": { "total_rows": N, ... },
            "cluster_labels": [0, 0, 1, -1, 2, ...]
        }
    """
    print("[2/6] Loading pre-computed cluster labels...")
    
    if not os.path.exists(json_path):
        raise FileNotFoundError(
            f"Cluster labels file not found: {json_path}\n"
            f"Run cluster.py externally first, then place cluster_labels.json "
            f"in the backend/ directory."
        )
    
    with open(json_path, "r") as f:
        data = json.load(f)
    
    labels = data["cluster_labels"]
    metadata = data.get("metadata", {})
    
    # Handle subset clustering: truncate DataFrame to match label count
    if len(labels) < len(df):
        print(f"  Note: labels cover {len(labels):,} of {len(df):,} rows "
              f"(subset clustering). Truncating DataFrame to match.")
        df = df.head(len(labels)).reset_index(drop=True)
    elif len(labels) > len(df):
        raise ValueError(
            f"Row count mismatch: cluster_labels.json has {len(labels):,} labels "
            f"but the cleaned DataFrame has only {len(df):,} rows.\n"
            f"Make sure you run cluster.py on the same CSV file."
        )
    
    df["cluster_id"] = labels
    
    n_clusters = len(set(labels)) - (1 if -1 in labels else 0)
    n_noise = labels.count(-1)
    
    print(f"  Loaded labels from: {json_path}")
    print(f"  DBSCAN params used: eps={metadata.get('eps_meters', '?')}m, "
          f"min_samples={metadata.get('min_samples', '?')}")
    print(f"  Clusters: {n_clusters}")
    print(f"  Noise points (unclustered): {n_noise:,}")
    
    return df


def extract_zone_name(locations: pd.Series) -> str:
    """Extract the most meaningful zone name from location strings."""
    # Get the most common road/area name
    all_parts = []
    for loc in locations:
        if not loc:
            continue
        # Extract road/area names before "Bengaluru"
        parts = loc.split(",")
        if parts:
            # First part is usually the road name
            road = parts[0].strip()
            if road and len(road) > 3:
                all_parts.append(road)
            # Second part often has area name
            if len(parts) > 1:
                area = parts[1].strip()
                if area and len(area) > 3 and "Bengaluru" not in area:
                    all_parts.append(area)

    if not all_parts:
        return "Unnamed Zone"

    # Find the most frequent name
    counter = Counter(all_parts)
    most_common = counter.most_common(2)
    
    primary = most_common[0][0]
    
    # If we have a second name that seems like an area, combine them
    if len(most_common) > 1:
        secondary = most_common[1][0]
        # Check if they're different types (road vs area)
        if ("Road" in primary or "Cross" in primary or "Main" in primary) and \
           ("Road" not in secondary and "Cross" not in secondary and "Main" not in secondary):
            return f"{secondary} - {primary} Zone"
        elif ("Road" in secondary or "Cross" in secondary or "Main" in secondary) and \
             ("Road" not in primary and "Cross" not in primary and "Main" not in primary):
            return f"{primary} - {secondary} Zone"
    
    return f"{primary} Zone"


def compute_cluster_analytics(df: pd.DataFrame) -> list:
    """
    Step 3: Compute per-cluster analytics.
    
    For each cluster, calculate:
    - Center coordinates
    - Zone name
    - Total violations
    - Vehicle distribution
    - Junction ratio
    - Avg resolution time
    - Top locations
    - Hourly distribution
    - Violation types
    """
    print("[3/6] Computing cluster analytics...")
    
    clustered = df[df["cluster_id"] != -1]
    clusters = []
    
    for cluster_id, group in clustered.groupby("cluster_id"):
        # Center coordinates
        center_lat = group["latitude"].mean()
        center_lon = group["longitude"].mean()
        
        # Zone naming
        zone_name = extract_zone_name(group["location"])
        
        # Total violations
        total_violations = len(group)
        
        # Vehicle distribution
        vehicle_dist = group["vehicle_type_clean"].value_counts().to_dict()
        
        # Vehicle impact score (weighted average)
        vehicle_weights = group["vehicle_type_clean"].map(VEHICLE_WEIGHTS).fillna(2)
        avg_vehicle_weight = vehicle_weights.mean()
        
        # Junction ratio
        junction_ratio = group["is_junction"].mean()
        
        # Average resolution time
        valid_resolution = group["resolution_hours"].dropna()
        avg_resolution = valid_resolution.mean() if len(valid_resolution) > 0 else 0
        
        # Top locations
        loc_counts = group["location"].value_counts().head(5)
        top_locations = [
            {"name": loc.split(",")[0].strip(), "count": int(cnt)}
            for loc, cnt in loc_counts.items() if loc
        ]
        
        # Hourly distribution
        hourly_dist = group["hour"].value_counts().sort_index().to_dict()
        hourly_dist = {str(k): int(v) for k, v in hourly_dist.items()}
        
        # Police station (most common)
        police_station = group["police_station"].mode().iloc[0] if len(group["police_station"].mode()) > 0 else "Unknown"
        
        # Violation types (parse from violation_type column)
        violation_types = {}
        for vt in group["violation_type"].dropna():
            # Parse the JSON-like violation_type field
            try:
                types = json.loads(vt.replace('""', '"'))
                if isinstance(types, list):
                    for t in types:
                        clean_type = t.strip().strip('"')
                        violation_types[clean_type] = violation_types.get(clean_type, 0) + 1
            except (json.JSONDecodeError, AttributeError):
                pass
        
        # Top vehicle types sorted
        top_vehicles = [
            {"type": vtype, "count": int(cnt)}
            for vtype, cnt in sorted(vehicle_dist.items(), key=lambda x: -x[1])[:5]
        ]
        
        clusters.append({
            "cluster_id": int(cluster_id),
            "center_lat": float(center_lat),
            "center_lon": float(center_lon),
            "zone_name": zone_name,
            "total_violations": int(total_violations),
            "vehicle_distribution": vehicle_dist,
            "avg_vehicle_weight": float(avg_vehicle_weight),
            "junction_ratio": float(junction_ratio),
            "avg_resolution_time": float(avg_resolution) if not np.isnan(avg_resolution) else 0.0,
            "top_locations": top_locations,
            "hourly_distribution": hourly_dist,
            "police_station": str(police_station),
            "violation_types": violation_types,
            "top_vehicles": top_vehicles,
            "top_vehicle_type": top_vehicles[0]["type"] if top_vehicles else "UNKNOWN",
        })
    
    print(f"  Computed analytics for {len(clusters)} clusters")
    return clusters


def compute_impact_scores(clusters: list) -> list:
    """
    Step 4: Compute Impact Scores for all clusters.
    
    Impact Score = 0.45 × Violation Density
                 + 0.25 × Vehicle Impact
                 + 0.15 × Junction Impact
                 + 0.15 × Enforcement Difficulty
    
    All components are normalized to [0, 1] then scaled to 0-100.
    """
    print("[4/6] Computing Impact Scores...")
    
    if not clusters:
        return clusters
    
    # Extract raw values
    violations = np.array([c["total_violations"] for c in clusters])
    vehicle_weights = np.array([c["avg_vehicle_weight"] for c in clusters])
    junction_ratios = np.array([c["junction_ratio"] for c in clusters])
    resolution_times = np.array([c["avg_resolution_time"] for c in clusters])
    
    # Normalize each component to [0, 1]
    def normalize(arr):
        min_val, max_val = arr.min(), arr.max()
        if max_val == min_val:
            return np.zeros_like(arr)
        return (arr - min_val) / (max_val - min_val)
    
    norm_violations = normalize(violations)
    norm_vehicle = normalize(vehicle_weights)
    norm_junction = normalize(junction_ratios)
    norm_resolution = normalize(resolution_times)
    
    # Compute impact score
    impact_scores = (
        0.45 * norm_violations +
        0.25 * norm_vehicle +
        0.15 * norm_junction +
        0.15 * norm_resolution
    ) * 100
    
    # Compute percentiles for density map
    p25 = np.percentile(violations, 25)
    p50 = np.percentile(violations, 50)
    p75 = np.percentile(violations, 75)
    p90 = np.percentile(violations, 90)
    
    # Compute impact score percentiles for zone classification
    ip25 = np.percentile(impact_scores, 25)
    ip50 = np.percentile(impact_scores, 50)
    ip75 = np.percentile(impact_scores, 75)
    ip90 = np.percentile(impact_scores, 90)
    
    for i, cluster in enumerate(clusters):
        cluster["impact_score"] = float(round(impact_scores[i], 1))
        cluster["vehicle_impact_score"] = float(norm_vehicle[i])
        
        # Density percentile
        v = cluster["total_violations"]
        if v >= p90:
            cluster["violation_percentile"] = "P90"
        elif v >= p75:
            cluster["violation_percentile"] = "P75"
        elif v >= p50:
            cluster["violation_percentile"] = "P50"
        else:
            cluster["violation_percentile"] = "P25"
        
        # Impact percentile (for zone classification)
        s = impact_scores[i]
        if s >= ip90:
            cluster["impact_percentile"] = "P90"
        elif s >= ip75:
            cluster["impact_percentile"] = "P75"
        elif s >= ip50:
            cluster["impact_percentile"] = "P50"
        else:
            cluster["impact_percentile"] = "P25"
    
    # Sort and rank by impact score (descending)
    clusters.sort(key=lambda x: -x["impact_score"])
    for rank, cluster in enumerate(clusters, 1):
        cluster["impact_rank"] = rank
    
    # Sort and rank by violations (descending) for density rank
    clusters_by_density = sorted(clusters, key=lambda x: -x["total_violations"])
    for rank, cluster in enumerate(clusters_by_density, 1):
        cluster["density_rank"] = rank
    
    print(f"  Impact scores range: {min(c['impact_score'] for c in clusters):.1f} - "
          f"{max(c['impact_score'] for c in clusters):.1f}")
    print(f"  Impact percentile thresholds: P25={ip25:.1f}, P50={ip50:.1f}, "
          f"P75={ip75:.1f}, P90={ip90:.1f}")
    
    return clusters


def generate_all_recommendations(clusters: list) -> list:
    """
    Step 5: Classify zones and generate rule-engine recommendations.
    
    Uses the Zone Classification Engine to categorize each zone, then
    the Rule Engine to produce deterministic recommendations.
    Gemini explanations are NOT generated here — they are on-demand via API.
    """
    print("[5/6] Classifying zones & generating recommendations...")
    
    all_recommendations = []
    classification_counts = {}
    
    for cluster in clusters:
        zone_data = {
            "zone_id": cluster["cluster_id"],
            "zone_name": cluster["zone_name"],
            "impact_score": cluster["impact_score"],
            "total_violations": cluster["total_violations"],
            "violation_percentile": cluster.get("violation_percentile", "P25"),
            "impact_percentile": cluster.get("impact_percentile", "P25"),
            "vehicle_impact_score": cluster.get("vehicle_impact_score", 0),
            "junction_ratio": cluster["junction_ratio"],
            "avg_resolution_time": cluster["avg_resolution_time"],
            "top_vehicle_type": cluster.get("top_vehicle_type", "UNKNOWN"),
            "density_rank": cluster.get("density_rank", 999),
            "impact_rank": cluster.get("impact_rank", 999),
            "top_locations": cluster.get("top_locations", []),
        }
        
        zone_rec = generate_zone_recommendation(zone_data)
        all_recommendations.append(zone_rec)
        
        # Store classification on the cluster for JSON output
        cluster["zone_classification"] = zone_rec["zone_classification"]
        
        # Count classifications
        cls = zone_rec["zone_classification"]
        classification_counts[cls] = classification_counts.get(cls, 0) + 1
    
    print(f"  Generated recommendations for {len(all_recommendations)} zones")
    for cls, count in sorted(classification_counts.items()):
        print(f"    {cls}: {count}")
    
    return all_recommendations


def save_to_database(clusters: list, recommendations: list):
    """
    Step 6: Persist processed data to the database.
    """
    print("[6/6] Saving to database...")
    
    db = SessionLocal()
    try:
        # Clear existing data
        db.query(Recommendation).delete()
        db.query(HotspotDetail).delete()
        db.query(Hotspot).delete()
        db.commit()
        
        for cluster in clusters:
            # Save hotspot
            hotspot = Hotspot(
                zone_id=cluster["cluster_id"],
                zone_name=cluster["zone_name"],
                center_lat=cluster["center_lat"],
                center_lon=cluster["center_lon"],
                impact_score=cluster["impact_score"],
                rank=cluster["impact_rank"],
                density_rank=cluster["density_rank"],
                total_violations=cluster["total_violations"],
                violation_percentile=cluster["violation_percentile"],
                police_station=cluster["police_station"],
            )
            db.add(hotspot)
            
            # Save hotspot details
            detail = HotspotDetail(
                zone_id=cluster["cluster_id"],
                vehicle_distribution=cluster["vehicle_distribution"],
                top_locations=cluster["top_locations"],
                hourly_distribution=cluster["hourly_distribution"],
                junction_ratio=cluster["junction_ratio"],
                avg_resolution_time=cluster["avg_resolution_time"],
                violation_types=cluster.get("violation_types", {}),
                top_vehicles=cluster.get("top_vehicles", []),
            )
            db.add(detail)
        
        # Save recommendations (new format: one row per zone per recommendation)
        rec_count = 0
        for zone_rec in recommendations:
            for rec_text in zone_rec.get("recommendations", []):
                recommendation = Recommendation(
                    zone_id=zone_rec["zone_id"],
                    action=rec_text,
                    reason=zone_rec.get("zone_classification", "Moderate Zone"),
                    priority=zone_rec.get("priority", "Medium"),
                    expected_benefit="",
                    category=zone_rec.get("zone_classification", "General"),
                )
                db.add(recommendation)
                rec_count += 1
        
        db.commit()
        print(f"  Saved {len(clusters)} hotspots and {rec_count} recommendations")
        
    except Exception as e:
        db.rollback()
        print(f"  Database error: {e}")
        raise
    finally:
        db.close()


def save_to_json(clusters: list, recommendations: list, output_dir: str = "."):
    """
    Alternative: Save processed data as JSON files (for when DB is unavailable).
    """
    os.makedirs(output_dir, exist_ok=True)
    
    with open(os.path.join(output_dir, "hotspots.json"), "w") as f:
        json.dump(clusters, f, indent=2, default=str)
    
    with open(os.path.join(output_dir, "recommendations.json"), "w") as f:
        json.dump(recommendations, f, indent=2, default=str)
    
    print(f"  Saved JSON files to {output_dir}")


def run_pipeline(csv_path: str = None, cluster_json_path: str = None):
    """
    Run the complete data processing pipeline.
    
    Args:
        csv_path:          Path to the raw CSV file.
        cluster_json_path: Path to the pre-computed cluster_labels.json
                           (generated by cluster.py).
    """
    backend_dir = os.path.dirname(os.path.abspath(__file__))
    
    if csv_path is None:
        csv_path = os.path.join(os.path.dirname(backend_dir), "sample.csv")
        if not os.path.exists(csv_path):
            csv_path = os.path.join(backend_dir, "..", "sample.csv")
    
    if cluster_json_path is None:
        cluster_json_path = os.path.join(backend_dir, "cluster_labels.json")
    
    print("=" * 60)
    print("ParkWise AI - Data Processing Pipeline")
    print("=" * 60)
    
    # Step 1: Load and clean data
    df = load_and_clean_data(csv_path)
    
    # Step 2: Load pre-computed cluster labels
    df = load_cluster_labels(df, cluster_json_path)
    
    # Step 3: Compute cluster analytics
    clusters = compute_cluster_analytics(df)
    
    # Step 4: Compute impact scores
    clusters = compute_impact_scores(clusters)
    
    # Step 5: Generate recommendations
    recommendations = generate_all_recommendations(clusters)
    
    # Step 6: Save data
    try:
        init_db()
        save_to_database(clusters, recommendations)
    except Exception as e:
        print(f"  Warning: Database save failed ({e}). Saving to JSON instead.")
    
    # Always save JSON as backup / for frontend fallback
    data_dir = os.path.join(backend_dir, "data")
    save_to_json(clusters, recommendations, data_dir)
    
    print("=" * 60)
    print("Pipeline completed successfully!")
    print(f"  Total zones: {len(clusters)}")
    print(f"  Total recommendations: {len(recommendations)}")
    if clusters:
        print(f"  Highest impact zone: {clusters[0]['zone_name']} "
              f"(score: {clusters[0]['impact_score']})")
    print("=" * 60)
    
    return clusters, recommendations


if __name__ == "__main__":
    run_pipeline()
