"""
ParkWise AI — Gemini 2.5 Flash Explanation Engine

Purpose: Generate human-readable explanations for rule-engine recommendations.
The LLM does NOT make decisions — it only explains decisions already made by the
Zone Classification Engine + Rule Engine.

Architecture:
    Rule Engine Output  →  Gemini 2.5 Flash  →  Explanation
"""

import os
import json
from dotenv import load_dotenv

load_dotenv()

GEMINI_API_KEY = os.getenv("GEMINI_API_KEY", "")

# ============================================================
# Prompts
# ============================================================

SYSTEM_PROMPT = """You are an urban traffic management expert.

You analyze parking violation hotspots and generate professional operational insights.

Rules:

1. Never invent data.
2. Use only supplied hotspot information.
3. Keep explanations concise.
4. Explain why the recommendation exists.
5. Focus on actionable intelligence.
6. Do not create new recommendations.
7. Explain the recommendations generated by the rule engine.

Output format: Return ONLY valid JSON with these exact keys:
{
  "risk_summary": "...",
  "key_risk_factors": ["...", "..."],
  "recommendation_explanation": "...",
  "expected_benefit": "..."
}

Do not include markdown formatting, code fences, or any text outside the JSON object."""

USER_PROMPT_TEMPLATE = """Analyze the following hotspot.

Zone Name:
{zone_name}

Zone Classification:
{zone_classification}

Density Rank:
#{density_rank}

Density Percentile:
{density_percentile}

Impact Score:
{impact_score}

Impact Rank:
#{impact_rank}

Total Violations:
{total_violations}

Top Roads:
{top_roads}

Rule Engine Recommendations:
{recommendations}

Generate:

1. Risk Summary
2. Key Risk Factors
3. Recommendation Explanation
4. Expected Benefit

Maximum 120 words."""


# ============================================================
# Gemini API Call
# ============================================================

def _call_gemini(prompt: str) -> dict:
    """
    Call Gemini 2.5 Flash via the google-genai SDK.

    Returns parsed JSON dict or raises an exception.
    """
    from google import genai

    client = genai.Client(api_key=GEMINI_API_KEY)

    response = client.models.generate_content(
        model="gemini-2.5-flash",
        contents=prompt,
        config={
            "system_instruction": SYSTEM_PROMPT,
            "temperature": 0.3,
            "max_output_tokens": 500,
        },
    )

    text = response.text.strip()

    # Strip markdown code fences if present
    if text.startswith("```"):
        lines = text.split("\n")
        # Remove first and last lines (the fences)
        lines = [l for l in lines if not l.strip().startswith("```")]
        text = "\n".join(lines).strip()

    return json.loads(text)


# ============================================================
# Public API
# ============================================================

def generate_explanation(zone_rec: dict) -> dict:
    """
    Generate an AI explanation for a zone's rule-engine recommendations.

    Args:
        zone_rec: Output of recommendations.generate_zone_recommendation()
            Must contain: zone_name, zone_classification, density_rank,
            violation_percentile, impact_score, impact_rank,
            total_violations, top_roads, recommendations

    Returns:
        {
            "risk_summary": str,
            "key_risk_factors": [str, ...],
            "recommendation_explanation": str,
            "expected_benefit": str,
        }

    If the API key is missing or the call fails, returns a structured
    fallback response.
    """
    if not GEMINI_API_KEY:
        return _fallback_explanation(zone_rec)

    try:
        prompt = USER_PROMPT_TEMPLATE.format(
            zone_name=zone_rec.get("zone_name", "Unknown"),
            zone_classification=zone_rec.get("zone_classification", "Unknown"),
            density_rank=zone_rec.get("density_rank", "N/A"),
            density_percentile=zone_rec.get("violation_percentile", "N/A"),
            impact_score=zone_rec.get("impact_score", 0),
            impact_rank=zone_rec.get("impact_rank", "N/A"),
            total_violations=zone_rec.get("total_violations", 0),
            top_roads=", ".join(zone_rec.get("top_roads", [])) or "N/A",
            recommendations="\n".join(
                f"- {r}" for r in zone_rec.get("recommendations", [])
            ),
        )

        result = _call_gemini(prompt)

        # Validate expected keys
        return {
            "risk_summary": result.get("risk_summary", ""),
            "key_risk_factors": result.get("key_risk_factors", []),
            "recommendation_explanation": result.get("recommendation_explanation", ""),
            "expected_benefit": result.get("expected_benefit", ""),
        }

    except Exception as e:
        print(f"  [Gemini] Error generating explanation for "
              f"{zone_rec.get('zone_name', '?')}: {e}")
        return _fallback_explanation(zone_rec)


def _fallback_explanation(zone_rec: dict) -> dict:
    """
    Generate a deterministic fallback explanation when Gemini is unavailable.
    """
    zone_name = zone_rec.get("zone_name", "This zone")
    classification = zone_rec.get("zone_classification", "Moderate Zone")
    impact_score = zone_rec.get("impact_score", 0)
    total = zone_rec.get("total_violations", 0)
    density_rank = zone_rec.get("density_rank", "N/A")
    impact_rank = zone_rec.get("impact_rank", "N/A")

    risk_summary = (
        f"{zone_name} is classified as a {classification} with an impact score "
        f"of {impact_score:.1f}/100 and {total:,} recorded violations."
    )

    factors = []
    if total > 500:
        factors.append("High volume of parking violations indicating chronic non-compliance")
    if zone_rec.get("junction_ratio", 0) > 0.4:
        factors.append("Significant proportion of violations near junctions")
    if zone_rec.get("vehicle_impact_score", 0) > 0.5:
        factors.append("Presence of larger vehicles increasing road blockage")
    if not factors:
        factors.append("Violation patterns consistent with zone classification")

    rec_explanation = (
        f"The rule engine has generated recommendations based on the "
        f"{classification} classification. "
        f"Density rank #{density_rank} and impact rank #{impact_rank} "
        f"inform the priority and type of interventions suggested."
    )

    expected_benefit = (
        "Implementation of the recommended actions is expected to reduce "
        "parking violations, improve traffic flow, and enhance road safety "
        "in the affected area."
    )

    return {
        "risk_summary": risk_summary,
        "key_risk_factors": factors,
        "recommendation_explanation": rec_explanation,
        "expected_benefit": expected_benefit,
    }
