"""
ParkWise AI — Gemini 2.5 Flash Explanation Engine

Generates human-readable explanations for rule-engine recommendations
using the Emergent Universal LLM Key via emergentintegrations.

The LLM does NOT make decisions — it only explains decisions already
produced by the Zone Classification Engine + Rule Engine.
"""

import os
import json
import asyncio
import uuid
from dotenv import load_dotenv

load_dotenv()

EMERGENT_LLM_KEY = os.environ.get("EMERGENT_LLM_KEY", "")


SYSTEM_PROMPT = """You are an urban traffic management expert.

You analyze parking violation hotspots and generate professional operational insights.

Rules:

1. Never invent data.
2. Use only supplied hotspot information.
3. Keep explanations concise.
4. Explain why the recommendation exists.
5. Focus on actionable intelligence.
6. Do not create new recommendations.
7. Explain the recommendations generated by the rule engine.

Output format: Return ONLY valid JSON with these exact keys:
{
  "risk_summary": "...",
  "key_risk_factors": ["...", "..."],
  "recommendation_explanation": "...",
  "expected_benefit": "..."
}

Do not include markdown formatting, code fences, or any text outside the JSON object."""


USER_PROMPT_TEMPLATE = """Analyze the following hotspot.

Zone Name:
{zone_name}

Zone Classification:
{zone_classification}

Density Rank:
#{density_rank}

Density Percentile:
{density_percentile}

Impact Score:
{impact_score}

Impact Rank:
#{impact_rank}

Total Violations:
{total_violations}

Top Roads:
{top_roads}

Rule Engine Recommendations:
{recommendations}

Generate:

1. Risk Summary
2. Key Risk Factors
3. Recommendation Explanation
4. Expected Benefit

Maximum 120 words."""


def _call_gemini_sync(prompt: str) -> dict:
    """Run the LlmChat call synchronously using a fresh event loop in a
    background thread so it works even when called from inside FastAPI's
    running event loop."""
    import threading

    from emergentintegrations.llm.chat import LlmChat, UserMessage

    result_box = {"text": None, "error": None}

    def _worker():
        try:
            async def _run():
                chat = LlmChat(
                    api_key=EMERGENT_LLM_KEY,
                    session_id=f"parkwise-{uuid.uuid4()}",
                    system_message=SYSTEM_PROMPT,
                ).with_model("gemini", "gemini-2.5-flash")
                return await chat.send_message(UserMessage(text=prompt))

            loop = asyncio.new_event_loop()
            try:
                result_box["text"] = loop.run_until_complete(_run())
            finally:
                loop.close()
        except Exception as e:
            result_box["error"] = e

    t = threading.Thread(target=_worker)
    t.start()
    t.join(timeout=60)

    if result_box["error"]:
        raise result_box["error"]
    if result_box["text"] is None:
        raise TimeoutError("Gemini call timed out")

    text = (result_box["text"] or "").strip()

    if text.startswith("```"):
        lines = [l for l in text.split("\n") if not l.strip().startswith("```")]
        text = "\n".join(lines).strip()

    return json.loads(text)


def generate_explanation(zone_rec: dict) -> dict:
    """
    Generate an AI explanation for a zone's rule-engine recommendations.
    Returns a deterministic fallback if the API key is missing or call fails.
    """
    if not EMERGENT_LLM_KEY:
        return _fallback_explanation(zone_rec)

    try:
        prompt = USER_PROMPT_TEMPLATE.format(
            zone_name=zone_rec.get("zone_name", "Unknown"),
            zone_classification=zone_rec.get("zone_classification", "Unknown"),
            density_rank=zone_rec.get("density_rank", "N/A"),
            density_percentile=zone_rec.get("violation_percentile", "N/A"),
            impact_score=zone_rec.get("impact_score", 0),
            impact_rank=zone_rec.get("impact_rank", "N/A"),
            total_violations=zone_rec.get("total_violations", 0),
            top_roads=", ".join(zone_rec.get("top_roads", [])) or "N/A",
            recommendations="\n".join(
                f"- {r}" for r in zone_rec.get("recommendations", [])
            ),
        )

        result = _call_gemini_sync(prompt)

        return {
            "risk_summary": result.get("risk_summary", ""),
            "key_risk_factors": result.get("key_risk_factors", []),
            "recommendation_explanation": result.get("recommendation_explanation", ""),
            "expected_benefit": result.get("expected_benefit", ""),
        }

    except Exception as e:
        print(f"[gemini] Error for {zone_rec.get('zone_name', '?')}: {e}")
        return _fallback_explanation(zone_rec)


def _fallback_explanation(zone_rec: dict) -> dict:
    zone_name = zone_rec.get("zone_name", "This zone")
    classification = zone_rec.get("zone_classification", "Moderate Zone")
    impact_score = zone_rec.get("impact_score", 0)
    total = zone_rec.get("total_violations", 0)
    density_rank = zone_rec.get("density_rank", "N/A")
    impact_rank = zone_rec.get("impact_rank", "N/A")

    risk_summary = (
        f"{zone_name} is classified as a {classification} with an impact score "
        f"of {impact_score:.1f}/100 and {total:,} recorded violations."
    )

    factors = []
    if total > 500:
        factors.append("High volume of parking violations indicating chronic non-compliance")
    if zone_rec.get("junction_ratio", 0) > 0.4:
        factors.append("Significant proportion of violations near junctions")
    if zone_rec.get("vehicle_impact_score", 0) > 0.5:
        factors.append("Presence of larger vehicles increasing road blockage")
    if not factors:
        factors.append("Violation patterns consistent with zone classification")

    rec_explanation = (
        f"The rule engine has generated recommendations based on the "
        f"{classification} classification. Density rank #{density_rank} and "
        f"impact rank #{impact_rank} inform the priority and type of "
        f"interventions suggested."
    )

    expected_benefit = (
        "Implementation of the recommended actions is expected to reduce "
        "parking violations, improve traffic flow, and enhance road safety "
        "in the affected area."
    )

    return {
        "risk_summary": risk_summary,
        "key_risk_factors": factors,
        "recommendation_explanation": rec_explanation,
        "expected_benefit": expected_benefit,
    }
