"""
ParkWise AI - FastAPI Backend

Serves the processed parking violation data via REST APIs.
"""

import os
import json
import threading
import pandas as pd
from fastapi import FastAPI, HTTPException
from fastapi.middleware.cors import CORSMiddleware
from fastapi.responses import JSONResponse

app = FastAPI(
    title="ParkWise AI",
    description="Parking Enforcement Intelligence Platform API",
    version="1.0.0",
)

# CORS - allow frontend to connect
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

# ============================================================
# Data Loading - Load from JSON files (generated by pipeline)
# ============================================================
DATA_DIR = os.path.join(os.path.dirname(__file__), "data")
HOTSPOTS = []
RECOMMENDATIONS = []

# Percentile bands shared by the Impact map and dashboard Severity Mix
PERCENTILE_SEVERITY = {
    "P90": ("Critical", "#EF4444"),
    "P75": ("High", "#F97316"),
    "P50": ("Moderate", "#EAB308"),
    "P25": ("Low", "#22C55E"),
}


def severity_from_percentile(percentile: str) -> tuple[str, str]:
    """Map P90/P75/P50/P25 percentile band to severity label and color."""
    return PERCENTILE_SEVERITY.get(percentile, PERCENTILE_SEVERITY["P25"])
# In-memory analytics cache (violations loaded from database on demand)
_ANALYTICS_CACHE = {}
_CACHE_LOCK = threading.Lock()
_COMPUTE_LOCK = threading.Lock()


def load_data():
    """Load processed data from JSON files."""
    global HOTSPOTS, RECOMMENDATIONS
    
    hotspots_path = os.path.join(DATA_DIR, "hotspots.json")
    recommendations_path = os.path.join(DATA_DIR, "recommendations.json")
    
    if os.path.exists(hotspots_path):
        with open(hotspots_path, "r") as f:
            HOTSPOTS = json.load(f)
        print(f"Loaded {len(HOTSPOTS)} hotspots from JSON")
    else:
        print(f"Warning: {hotspots_path} not found. Run data_processor.py first.")
    
    if os.path.exists(recommendations_path):
        with open(recommendations_path, "r") as f:
            RECOMMENDATIONS = json.load(f)
        print(f"Loaded {len(RECOMMENDATIONS)} recommendations from JSON")


def init_violation_data():
    """Initialize violation store and optionally preload data into memory for fast filtering."""
    try:
        from violation_store import init_violation_store, load_violations_df_to_memory
        if not init_violation_store():
            return
        preload = os.getenv("PRELOAD_VIOLATIONS", "true").lower() in ("1", "true", "yes")
        if preload:
            load_violations_df_to_memory()
        else:
            print("PRELOAD_VIOLATIONS=false — date filters will query Supabase per request")
    except Exception as e:
        print(f"Error initializing violation store: {e}")


def _compute_filtered_data(start_date: str = None, end_date: str = None):
    from violation_store import (
        is_violation_store_ready,
        is_violations_df_loaded,
        load_violations_dataframe,
        load_violations_df_to_memory,
    )

    if not is_violation_store_ready():
        init_violation_data()

    if not is_violation_store_ready():
        print("Warning: violation store not ready. Falling back to full precomputed dataset.")
        return HOTSPOTS, RECOMMENDATIONS

    preload = os.getenv("PRELOAD_VIOLATIONS", "true").lower() in ("1", "true", "yes")
    if preload and not is_violations_df_loaded():
        load_violations_df_to_memory()

    filtered_df = load_violations_dataframe(start_date=start_date, end_date=end_date)

    if filtered_df.empty:
        return [], []

    from data_processor import compute_cluster_analytics, compute_impact_scores, generate_all_recommendations
    clusters = compute_cluster_analytics(filtered_df)
    clusters = compute_impact_scores(clusters)
    recs = generate_all_recommendations(clusters)
    return clusters, recs


def get_filtered_data(start_date: str = None, end_date: str = None):
    """
    Get hotspots and recommendations filtered by date range.
    If no dates are provided, return the full precomputed data.
    Uses thread-safe cache to avoid redundant evaluations.
    """
    cache_key = (start_date, end_date)

    with _CACHE_LOCK:
        if cache_key in _ANALYTICS_CACHE:
            return _ANALYTICS_CACHE[cache_key]

    if not start_date and not end_date:
        return HOTSPOTS, RECOMMENDATIONS

    try:
        with _COMPUTE_LOCK:
            with _CACHE_LOCK:
                if cache_key in _ANALYTICS_CACHE:
                    return _ANALYTICS_CACHE[cache_key]

            result = _compute_filtered_data(start_date, end_date)

            with _CACHE_LOCK:
                if len(_ANALYTICS_CACHE) > 100:
                    _ANALYTICS_CACHE.clear()
                _ANALYTICS_CACHE[cache_key] = result

            return result
    except Exception as e:
        print(f"Error filtering data: {e}")
        return HOTSPOTS, RECOMMENDATIONS


@app.on_event("startup")
async def startup():
    """Load data on application startup."""
    load_data()
    threading.Thread(target=init_violation_data, daemon=True).start()


# ============================================================
# API Endpoints
# ============================================================

@app.get("/")
async def root():
    """Health check endpoint."""
    from violation_store import violation_count, is_violations_df_loaded

    db_count = violation_count()
    return {
        "service": "ParkWise AI",
        "status": "active",
        "total_hotspots": len(HOTSPOTS),
        "total_recommendations": len(RECOMMENDATIONS),
        "violations_in_db": db_count,
        "violation_store_ready": db_count > 0,
        "violations_memory_loaded": is_violations_df_loaded(),
    }


@app.get("/api/date-range")
async def get_date_range():
    """
    Get the minimum and maximum dates available in the dataset.
    """
    from violation_store import cached_date_bounds, get_date_bounds, init_violation_store

    if not init_violation_store():
        return {
            "min_date": "2023-11-01",
            "max_date": "2024-04-30",
        }

    min_date, max_date = cached_date_bounds()
    if min_date is None or max_date is None:
        min_date, max_date = get_date_bounds()

    try:
        return {
            "min_date": min_date.strftime("%Y-%m-%d") if min_date and not pd.isnull(min_date) else "2023-11-01",
            "max_date": max_date.strftime("%Y-%m-%d") if max_date and not pd.isnull(max_date) else "2024-04-30",
        }
    except Exception as e:
        print(f"Error computing date range: {e}")
        return {
            "min_date": "2023-11-01",
            "max_date": "2024-04-30",
        }


@app.get("/api/hotspots")
async def get_hotspots(start_date: str = None, end_date: str = None):
    """
    Get all parking hotspots with coordinates and scores.
    Used for both density and impact map rendering.
    """
    hotspots, _ = get_filtered_data(start_date, end_date)
    if not hotspots:
        return []
    
    # Return simplified list for map rendering
    result = []
    for h in hotspots:
        result.append({
            "zone_id": h["cluster_id"],
            "zone_name": h["zone_name"],
            "lat": h["center_lat"],
            "lon": h["center_lon"],
            "impact_score": h["impact_score"],
            "impact_rank": h["impact_rank"],
            "density_rank": h["density_rank"],
            "total_violations": h["total_violations"],
            "violation_percentile": h["violation_percentile"],
            "police_station": h["police_station"],
            "hourly_distribution": h.get("hourly_distribution", {}),
        })
    
    return result


@app.get("/api/hotspot/{zone_id}")
async def get_hotspot_detail(zone_id: int, start_date: str = None, end_date: str = None):
    """
    Get detailed information for a specific hotspot zone.
    Includes zone_classification and string-based recommendations.
    """
    hotspots, recommendations = get_filtered_data(start_date, end_date)
    for h in hotspots:
        if h["cluster_id"] == zone_id:
            # Get zone recommendation object (new format)
            zone_rec = None
            for r in recommendations:
                if r["zone_id"] == zone_id:
                    zone_rec = r
                    break
            
            # Extract string recommendations list
            rec_strings = []
            zone_classification = h.get("zone_classification", "Moderate Zone")
            if zone_rec:
                rec_strings = zone_rec.get("recommendations", [])
                zone_classification = zone_rec.get("zone_classification", zone_classification)
            
            return {
                "zone_id": h["cluster_id"],
                "zone_name": h["zone_name"],
                "center_lat": h["center_lat"],
                "center_lon": h["center_lon"],
                "impact_score": h["impact_score"],
                "impact_rank": h["impact_rank"],
                "density_rank": h["density_rank"],
                "total_violations": h["total_violations"],
                "violation_percentile": h["violation_percentile"],
                "impact_percentile": h.get("impact_percentile", "P25"),
                "zone_classification": zone_classification,
                "police_station": h["police_station"],
                "vehicle_distribution": h.get("vehicle_distribution", {}),
                "top_locations": h.get("top_locations", []),
                "hourly_distribution": h.get("hourly_distribution", {}),
                "junction_ratio": h.get("junction_ratio", 0),
                "avg_resolution_time": h.get("avg_resolution_time", 0),
                "violation_types": h.get("violation_types", {}),
                "top_vehicles": h.get("top_vehicles", []),
                "recommendations": rec_strings,
            }
    
    raise HTTPException(status_code=404, detail=f"Zone {zone_id} not found")


@app.get("/api/density-map")
async def get_density_map(start_date: str = None, end_date: str = None):
    """
    Get hotspots formatted for the Violation Density Map.
    Colored by violation count percentiles.
    """
    hotspots, _ = get_filtered_data(start_date, end_date)
    if not hotspots:
        return []
    
    result = []
    for h in hotspots:
        # Color based on percentile
        percentile = h.get("violation_percentile", "P25")
        risk, color = severity_from_percentile(percentile)
        
        result.append({
            "zone_id": h["cluster_id"],
            "zone_name": h["zone_name"],
            "lat": h["center_lat"],
            "lon": h["center_lon"],
            "violations": h["total_violations"],
            "density_rank": h["density_rank"],
            "percentile": percentile,
            "color": color,
            "risk": risk,
        })
    
    return result


@app.get("/api/impact-map")
async def get_impact_map(start_date: str = None, end_date: str = None):
    """
    Get hotspots formatted for the Operational Impact Map.
    Colored by impact_percentile (adapts to actual data distribution).
    """
    hotspots, _ = get_filtered_data(start_date, end_date)
    if not hotspots:
        return []
    
    result = []
    for h in hotspots:
        # Use impact_percentile for coloring (relative to data)
        impact_pct = h.get("impact_percentile", "P25")
        severity, color = severity_from_percentile(impact_pct)
        
        result.append({
            "zone_id": h["cluster_id"],
            "zone_name": h["zone_name"],
            "lat": h["center_lat"],
            "lon": h["center_lon"],
            "impact_score": h["impact_score"],
            "impact_rank": h["impact_rank"],
            "impact_percentile": impact_pct,
            "color": color,
            "severity": severity,
        })
    
    return result


@app.get("/api/analytics")
async def get_analytics(start_date: str = None, end_date: str = None):
    """
    Get city-wide analytics summary.
    """
    hotspots, _ = get_filtered_data(start_date, end_date)
    if not hotspots:
        return {
            "total_zones": 0,
            "total_violations": 0,
            "avg_impact_score": 0.0,
            "severity_distribution": {
                "critical": 0,
                "high": 0,
                "moderate": 0,
                "low": 0,
            },
            "top_impact_zones": [],
            "top_density_zones": [],
            "overlooked_zones": [],
            "police_stations": [],
            "vehicle_distribution": {},
        }
    
    total_zones = len(hotspots)
    total_violations = sum(h["total_violations"] for h in hotspots)
    avg_impact = sum(h["impact_score"] for h in hotspots) / total_zones if total_zones > 0 else 0
    
    # Top 10 by impact
    sorted_by_impact = sorted(hotspots, key=lambda x: -x["impact_score"])[:10]
    top_impact = [
        {"zone_name": h["zone_name"], "impact_score": h["impact_score"],
         "impact_rank": h["impact_rank"], "zone_id": h["cluster_id"]}
        for h in sorted_by_impact
    ]
    
    # Top 10 by density
    sorted_by_density = sorted(hotspots, key=lambda x: -x["total_violations"])[:10]
    top_density = [
        {"zone_name": h["zone_name"], "total_violations": h["total_violations"],
         "density_rank": h["density_rank"], "zone_id": h["cluster_id"]}
        for h in sorted_by_density
    ]
    
    # Most overlooked zones (high impact rank, low density rank)
    overlooked = []
    for h in hotspots:
        if h["impact_rank"] <= 15 and h["density_rank"] > 20:
            overlooked.append({
                "zone_name": h["zone_name"],
                "impact_rank": h["impact_rank"],
                "density_rank": h["density_rank"],
                "impact_score": h["impact_score"],
                "zone_id": h["cluster_id"],
            })
    overlooked.sort(key=lambda x: x["impact_rank"])
    
    # Police station distribution
    station_counts = {}
    for h in hotspots:
        station = h.get("police_station", "Unknown")
        station_counts[station] = station_counts.get(station, 0) + 1
    
    police_stations = [
        {"station": s, "zones": c}
        for s, c in sorted(station_counts.items(), key=lambda x: -x[1])[:10]
    ]
    
    # Severity distribution — same percentile bands as the Operational Impact map
    critical = sum(1 for h in HOTSPOTS if h.get("impact_percentile") == "P90")
    high = sum(1 for h in HOTSPOTS if h.get("impact_percentile") == "P75")
    moderate = sum(1 for h in HOTSPOTS if h.get("impact_percentile") == "P50")
    low = sum(1 for h in HOTSPOTS if h.get("impact_percentile", "P25") == "P25")
    
    # Aggregate vehicle distribution
    all_vehicles = {}
    for h in hotspots:
        for vtype, count in h.get("vehicle_distribution", {}).items():
            all_vehicles[vtype] = all_vehicles.get(vtype, 0) + count
    
    return {
        "total_zones": total_zones,
        "total_violations": total_violations,
        "avg_impact_score": round(avg_impact, 1),
        "severity_distribution": {
            "critical": critical,
            "high": high,
            "moderate": moderate,
            "low": low,
        },
        "top_impact_zones": top_impact,
        "top_density_zones": top_density,
        "overlooked_zones": overlooked,
        "police_stations": police_stations,
        "vehicle_distribution": all_vehicles,
    }


@app.get("/api/recommendations")
async def get_recommendations(start_date: str = None, end_date: str = None):
    """
    Get all zone recommendations with classifications.
    Returns zone-level recommendation objects from the rule engine.
    """
    _, recommendations = get_filtered_data(start_date, end_date)
    if not recommendations:
        return {
            "total": 0,
            "by_classification": {},
            "by_priority": {"Critical": [], "High": [], "Medium": [], "Low": []},
            "classification_counts": {},
            "all": [],
        }
    
    # Group by classification
    by_classification = {}
    for rec in recommendations:
        cls = rec.get("zone_classification", "Moderate Zone")
        if cls not in by_classification:
            by_classification[cls] = []
        by_classification[cls].append(rec)
    
    # Group by priority
    by_priority = {"Critical": [], "High": [], "Medium": [], "Low": []}
    for rec in recommendations:
        priority = rec.get("priority", "Low")
        if priority in by_priority:
            by_priority[priority].append(rec)
    
    # Count classifications
    classification_counts = {
        cls: len(recs) for cls, recs in by_classification.items()
    }
    
    return {
        "total": len(recommendations),
        "by_classification": by_classification,
        "by_priority": by_priority,
        "classification_counts": classification_counts,
        "all": recommendations,
    }


@app.get("/api/recommendation/{zone_id}")
async def get_zone_recommendation(zone_id: int, start_date: str = None, end_date: str = None):
    """
    Get recommendation detail for a specific zone.
    Returns zone classification, rule-engine recommendations,
    and cached AI explanation (if available).
    """
    hotspots, recommendations = get_filtered_data(start_date, end_date)
    # Find the zone recommendation
    zone_rec = None
    for rec in recommendations:
        if rec.get("zone_id") == zone_id:
            zone_rec = rec
            break
    
    if not zone_rec:
        raise HTTPException(status_code=404, detail=f"No recommendation for zone {zone_id}")
    
    # Find zone details for extra context
    zone_detail = None
    for h in hotspots:
        if h.get("cluster_id") == zone_id:
            zone_detail = h
            break
    
    result = {**zone_rec}
    
    # Add cached explanation if it exists
    if zone_detail and "ai_explanation" in zone_detail:
        result["ai_explanation"] = zone_detail["ai_explanation"]
    
    return result


@app.post("/api/recommendation/{zone_id}/explain")
async def explain_zone_risk(zone_id: int, start_date: str = None, end_date: str = None):
    """
    Trigger Gemini 2.5 Flash to generate an explanation for a zone.
    The explanation is generated on-demand and cached in memory.
    """
    hotspots, recommendations = get_filtered_data(start_date, end_date)
    # Find the zone recommendation
    zone_rec = None
    for rec in recommendations:
        if rec.get("zone_id") == zone_id:
            zone_rec = rec
            break
    
    if not zone_rec:
        raise HTTPException(status_code=404, detail=f"No recommendation for zone {zone_id}")
    
    # Check if already cached on the hotspot
    for h in hotspots:
        if h.get("cluster_id") == zone_id and "ai_explanation" in h:
            return h["ai_explanation"]
    
    # Generate explanation via Gemini
    try:
        from gemini_engine import generate_explanation
        explanation = generate_explanation(zone_rec)
        
        # Cache on the hotspot object in memory
        for h in hotspots:
            if h.get("cluster_id") == zone_id:
                h["ai_explanation"] = explanation
                break
        
        return explanation
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"Explanation generation failed: {str(e)}")


@app.post("/api/process")
async def trigger_processing():
    """Trigger the data processing pipeline."""
    try:
        from data_processor import run_pipeline
        clusters, recommendations = run_pipeline()
        load_data()  # Reload the fresh data
        
        # Clear cache and reload violation store metadata
        with _CACHE_LOCK:
            _ANALYTICS_CACHE.clear()
        from violation_store import invalidate_violation_store_cache, init_violation_store, load_violations_df_to_memory
        invalidate_violation_store_cache()
        threading.Thread(
            target=lambda: init_violation_store(force=True) and load_violations_df_to_memory(force=True),
            daemon=True,
        ).start()
        
        return {
            "status": "success",
            "zones_processed": len(clusters),
            "recommendations_generated": len(recommendations),
        }
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))


@app.get("/api/trends/max-date")
async def get_trends_max_date():
    """
    Get the maximum date available in the dataset.
    """
    from violation_store import cached_date_bounds, get_date_bounds, init_violation_store

    if not init_violation_store():
        return {"max_date": "2024-04-08"}

    _, max_date = cached_date_bounds()
    if max_date is None:
        _, max_date = get_date_bounds()

    try:
        return {
            "max_date": max_date.strftime("%Y-%m-%d") if max_date and not pd.isnull(max_date) else "2024-04-08"
        }
    except Exception as e:
        print(f"Error computing trends max date: {e}")
        return {"max_date": "2024-04-08"}


@app.get("/api/check-raw-dates")
async def check_raw_dates():
    """Diagnostic endpoint to inspect violation datetimes in the database."""
    try:
        from violation_store import get_date_bounds, init_violation_store, violation_count

        if not init_violation_store():
            return {"error": "Violation store not ready. Run import_violations.py."}

        min_dt, max_dt = get_date_bounds()
        total = violation_count()

        return {
            "source": "database",
            "total_rows": total,
            "min_date": min_dt.strftime("%Y-%m-%d") if min_dt and not pd.isnull(min_dt) else "N/A",
            "max_date": max_dt.strftime("%Y-%m-%d") if max_dt and not pd.isnull(max_dt) else "N/A",
        }
    except Exception as e:
        return {"error": str(e)}


@app.get("/api/trends/debug-dates")
async def debug_dates():
    """Detailed debugging for datetimes in the violation database."""
    try:
        from violation_store import get_date_bounds, init_violation_store, violation_count

        if not init_violation_store():
            return {"status": "Violation store not ready"}

        min_dt, max_dt = get_date_bounds()
        total = violation_count()

        return {
            "source": "database",
            "total_rows": total,
            "min": str(min_dt),
            "max": str(max_dt),
        }
    except Exception as e:
        return {"error": str(e)}


@app.get("/api/trends/compare")
async def compare_zones_trends(zone_a: int, zone_b: int, start_hour: int, end_hour: int):
    """
    Filter data for Zone A and Zone B dynamically for the peak date and selected hour range.
    """
    from violation_store import init_violation_store, is_violations_df_loaded, load_violations_dataframe, load_violations_df_to_memory

    if not init_violation_store():
        raise HTTPException(
            status_code=503,
            detail="Violation database not ready. Run import_violations.py first.",
        )

    preload = os.getenv("PRELOAD_VIOLATIONS", "true").lower() in ("1", "true", "yes")
    if preload and not is_violations_df_loaded():
        load_violations_df_to_memory()

    try:
        from violation_store import cached_date_bounds, get_date_bounds

        _, max_date = cached_date_bounds()
        if max_date is None:
            _, max_date = get_date_bounds()

        if max_date is None or pd.isnull(max_date):
            max_date_utc = pd.to_datetime("2024-04-08", utc=True)
        else:
            max_date_utc = pd.to_datetime(max_date, utc=True)

        start_date = max_date_utc - pd.DateOffset(months=1)
        start_date_utc = pd.to_datetime(start_date, utc=True)
        start_bound = start_date_utc.date().isoformat()
        end_bound = max_date_utc.date().isoformat()

        df_filtered = load_violations_dataframe(
            start_date=start_bound,
            end_date=end_bound,
            min_hour=start_hour,
            max_hour=end_hour,
        )

        def get_zone_metrics(zone_id: int):
            zone_df = df_filtered[df_filtered["cluster_id"] == zone_id]
            
            # Find zone name and static details from HOTSPOTS
            zone_name = f"Zone {zone_id}"
            static_impact_score = 0.0
            for h in HOTSPOTS:
                if h["cluster_id"] == zone_id:
                    zone_name = h["zone_name"]
                    static_impact_score = h["impact_score"]
                    break
            
            if zone_df.empty:
                return {
                    "zone_id": zone_id,
                    "zone_name": zone_name,
                    "total_violations": 0,
                    "avg_vehicle_weight": 0.0,
                    "junction_ratio": 0.0,
                    "avg_resolution_time": 0.0,
                    "top_road": "N/A",
                    "top_locations": [],
                    "vehicle_distribution": {},
                    "violation_types": {},
                    "hourly_distribution": {},
                    "impact_score": static_impact_score,
                }
            
            total_violations = len(zone_df)
            
            # Vehicle weight mapping
            from data_processor import VEHICLE_WEIGHTS
            weights = zone_df["vehicle_type_clean"].map(VEHICLE_WEIGHTS).fillna(2)
            avg_weight = weights.mean()
            
            # Junction ratio
            junction_ratio = zone_df["is_junction"].mean()
            
            # Resolution hours
            valid_res = zone_df["resolution_hours"].dropna()
            avg_resolution = valid_res.mean() if len(valid_res) > 0 else 0.0
            
            # Top locations
            loc_counts = zone_df["location"].value_counts()
            top_road = loc_counts.index[0].split(",")[0].strip() if not loc_counts.empty else "N/A"
            top_locations = [
                {"name": loc.split(",")[0].strip(), "count": int(cnt)}
                for loc, cnt in loc_counts.head(5).items() if loc
            ]
            
            # Distributions
            vehicle_dist = zone_df["vehicle_type_clean"].value_counts().to_dict()
            hourly_dist = zone_df["hour"].value_counts().sort_index().to_dict()
            hourly_dist = {str(int(float(k))): int(v) for k, v in hourly_dist.items()}
            
            violation_types = {}
            for vt in zone_df["violation_type"].dropna():
                try:
                    types = json.loads(vt.replace('""', '"'))
                    if isinstance(types, list):
                        for t in types:
                            clean_type = t.strip().strip('"')
                            violation_types[clean_type] = violation_types.get(clean_type, 0) + 1
                except Exception:
                    pass
            
            # Format and sort for frontend top list
            sorted_violations = sorted(violation_types.items(), key=lambda x: -x[1])
            top_violation_types = [
                {"type": k, "count": int(v)}
                for k, v in sorted_violations[:5]
            ]
            
            return {
                "zone_id": zone_id,
                "zone_name": zone_name,
                "total_violations": total_violations,
                "avg_vehicle_weight": float(avg_weight),
                "junction_ratio": float(junction_ratio),
                "avg_resolution_time": float(avg_resolution),
                "top_road": top_road,
                "top_locations": top_locations,
                "vehicle_distribution": {k: int(v) for k, v in vehicle_dist.items()},
                "violation_types": violation_types,
                "top_violation_types": top_violation_types,
                "hourly_distribution": hourly_dist,
                "impact_score": static_impact_score,
            }

        metrics_a = get_zone_metrics(zone_a)
        metrics_b = get_zone_metrics(zone_b)

        return {
            "max_date": max_date_utc.strftime("%Y-%m-%d"),
            "start_hour": start_hour,
            "end_hour": end_hour,
            "zone_a": metrics_a,
            "zone_b": metrics_b,
        }
    except Exception as e:
        print(f"Error computing dynamic trends comparison: {e}")
        raise HTTPException(status_code=500, detail=str(e))


@app.post("/api/trends/explain")
async def explain_trends_comparison(request: dict):
    """
    Call Gemini model to recommend actions based on dynamic comparison metrics.
    """
    zone_a = request.get("zone_a")
    zone_b = request.get("zone_b")
    start_hour = request.get("start_hour", 0)
    end_hour = request.get("end_hour", 23)
    
    if not zone_a or not zone_b:
        raise HTTPException(status_code=400, detail="Missing zone details in request body")
        
    try:
        from gemini_engine import generate_trends_comparison
        suggestions = generate_trends_comparison(zone_a, zone_b, start_hour, end_hour)
        return suggestions
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))


if __name__ == "__main__":
    import uvicorn
    uvicorn.run("main:app", host="0.0.0.0", port=8000, reload=True)

