"""
ParkWise AI - FastAPI Backend

Serves the processed parking violation data via REST APIs.
"""

import os
import json
from fastapi import FastAPI, HTTPException
from fastapi.middleware.cors import CORSMiddleware
from fastapi.responses import JSONResponse

app = FastAPI(
    title="ParkWise AI",
    description="Parking Enforcement Intelligence Platform API",
    version="1.0.0",
)

# CORS - allow frontend to connect
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

# ============================================================
# Data Loading - Load from JSON files (generated by pipeline)
# ============================================================
DATA_DIR = os.path.join(os.path.dirname(__file__), "data")
HOTSPOTS = []
RECOMMENDATIONS = []


def load_data():
    """Load processed data from JSON files."""
    global HOTSPOTS, RECOMMENDATIONS
    
    hotspots_path = os.path.join(DATA_DIR, "hotspots.json")
    recommendations_path = os.path.join(DATA_DIR, "recommendations.json")
    
    if os.path.exists(hotspots_path):
        with open(hotspots_path, "r") as f:
            HOTSPOTS = json.load(f)
        print(f"Loaded {len(HOTSPOTS)} hotspots from JSON")
    else:
        print(f"Warning: {hotspots_path} not found. Run data_processor.py first.")
    
    if os.path.exists(recommendations_path):
        with open(recommendations_path, "r") as f:
            RECOMMENDATIONS = json.load(f)
        print(f"Loaded {len(RECOMMENDATIONS)} recommendations from JSON")


@app.on_event("startup")
async def startup():
    """Load data on application startup."""
    load_data()


# ============================================================
# API Endpoints
# ============================================================

@app.get("/")
async def root():
    """Health check endpoint."""
    return {
        "service": "ParkWise AI",
        "status": "active",
        "total_hotspots": len(HOTSPOTS),
        "total_recommendations": len(RECOMMENDATIONS),
    }


@app.get("/api/hotspots")
async def get_hotspots():
    """
    Get all parking hotspots with coordinates and scores.
    Used for both density and impact map rendering.
    """
    if not HOTSPOTS:
        raise HTTPException(status_code=404, detail="No hotspot data available. Run data processor first.")
    
    # Return simplified list for map rendering
    result = []
    for h in HOTSPOTS:
        result.append({
            "zone_id": h["cluster_id"],
            "zone_name": h["zone_name"],
            "lat": h["center_lat"],
            "lon": h["center_lon"],
            "impact_score": h["impact_score"],
            "impact_rank": h["impact_rank"],
            "density_rank": h["density_rank"],
            "total_violations": h["total_violations"],
            "violation_percentile": h["violation_percentile"],
            "police_station": h["police_station"],
        })
    
    return result


@app.get("/api/hotspot/{zone_id}")
async def get_hotspot_detail(zone_id: int):
    """
    Get detailed information for a specific hotspot zone.
    """
    for h in HOTSPOTS:
        if h["cluster_id"] == zone_id:
            # Get zone recommendations
            zone_recs = [r for r in RECOMMENDATIONS if r["zone_id"] == zone_id]
            
            return {
                "zone_id": h["cluster_id"],
                "zone_name": h["zone_name"],
                "center_lat": h["center_lat"],
                "center_lon": h["center_lon"],
                "impact_score": h["impact_score"],
                "impact_rank": h["impact_rank"],
                "density_rank": h["density_rank"],
                "total_violations": h["total_violations"],
                "violation_percentile": h["violation_percentile"],
                "police_station": h["police_station"],
                "vehicle_distribution": h.get("vehicle_distribution", {}),
                "top_locations": h.get("top_locations", []),
                "hourly_distribution": h.get("hourly_distribution", {}),
                "junction_ratio": h.get("junction_ratio", 0),
                "avg_resolution_time": h.get("avg_resolution_time", 0),
                "violation_types": h.get("violation_types", {}),
                "top_vehicles": h.get("top_vehicles", []),
                "recommendations": zone_recs,
            }
    
    raise HTTPException(status_code=404, detail=f"Zone {zone_id} not found")


@app.get("/api/density-map")
async def get_density_map():
    """
    Get hotspots formatted for the Violation Density Map.
    Colored by violation count percentiles.
    """
    if not HOTSPOTS:
        raise HTTPException(status_code=404, detail="No data available")
    
    result = []
    for h in HOTSPOTS:
        # Color based on percentile
        percentile = h.get("violation_percentile", "P25")
        if percentile == "P90":
            color = "#EF4444"    # Red - Critical
            risk = "Critical"
        elif percentile == "P75":
            color = "#F97316"    # Orange - High
            risk = "High"
        elif percentile == "P50":
            color = "#EAB308"    # Yellow - Moderate
            risk = "Moderate"
        else:
            color = "#22C55E"    # Green - Low
            risk = "Low"
        
        result.append({
            "zone_id": h["cluster_id"],
            "zone_name": h["zone_name"],
            "lat": h["center_lat"],
            "lon": h["center_lon"],
            "violations": h["total_violations"],
            "density_rank": h["density_rank"],
            "percentile": percentile,
            "color": color,
            "risk": risk,
        })
    
    return result


@app.get("/api/impact-map")
async def get_impact_map():
    """
    Get hotspots formatted for the Operational Impact Map.
    Colored by Impact Score severity bands.
    """
    if not HOTSPOTS:
        raise HTTPException(status_code=404, detail="No data available")
    
    result = []
    for h in HOTSPOTS:
        score = h["impact_score"]
        if score >= 75:
            color = "#EF4444"    # Red
            severity = "Critical"
        elif score >= 50:
            color = "#F97316"    # Orange
            severity = "High"
        elif score >= 25:
            color = "#EAB308"    # Yellow
            severity = "Moderate"
        else:
            color = "#22C55E"    # Green
            severity = "Low"
        
        result.append({
            "zone_id": h["cluster_id"],
            "zone_name": h["zone_name"],
            "lat": h["center_lat"],
            "lon": h["center_lon"],
            "impact_score": h["impact_score"],
            "impact_rank": h["impact_rank"],
            "color": color,
            "severity": severity,
        })
    
    return result


@app.get("/api/analytics")
async def get_analytics():
    """
    Get city-wide analytics summary.
    """
    if not HOTSPOTS:
        raise HTTPException(status_code=404, detail="No data available")
    
    total_zones = len(HOTSPOTS)
    total_violations = sum(h["total_violations"] for h in HOTSPOTS)
    avg_impact = sum(h["impact_score"] for h in HOTSPOTS) / total_zones if total_zones > 0 else 0
    
    # Top 10 by impact
    sorted_by_impact = sorted(HOTSPOTS, key=lambda x: -x["impact_score"])[:10]
    top_impact = [
        {"zone_name": h["zone_name"], "impact_score": h["impact_score"],
         "impact_rank": h["impact_rank"], "zone_id": h["cluster_id"]}
        for h in sorted_by_impact
    ]
    
    # Top 10 by density
    sorted_by_density = sorted(HOTSPOTS, key=lambda x: -x["total_violations"])[:10]
    top_density = [
        {"zone_name": h["zone_name"], "total_violations": h["total_violations"],
         "density_rank": h["density_rank"], "zone_id": h["cluster_id"]}
        for h in sorted_by_density
    ]
    
    # Most overlooked zones (high impact rank, low density rank)
    overlooked = []
    for h in HOTSPOTS:
        if h["impact_rank"] <= 15 and h["density_rank"] > 20:
            overlooked.append({
                "zone_name": h["zone_name"],
                "impact_rank": h["impact_rank"],
                "density_rank": h["density_rank"],
                "impact_score": h["impact_score"],
                "zone_id": h["cluster_id"],
            })
    overlooked.sort(key=lambda x: x["impact_rank"])
    
    # Police station distribution
    station_counts = {}
    for h in HOTSPOTS:
        station = h.get("police_station", "Unknown")
        station_counts[station] = station_counts.get(station, 0) + 1
    
    police_stations = [
        {"station": s, "zones": c}
        for s, c in sorted(station_counts.items(), key=lambda x: -x[1])[:10]
    ]
    
    # Severity distribution
    critical = sum(1 for h in HOTSPOTS if h["impact_score"] >= 75)
    high = sum(1 for h in HOTSPOTS if 50 <= h["impact_score"] < 75)
    moderate = sum(1 for h in HOTSPOTS if 25 <= h["impact_score"] < 50)
    low = sum(1 for h in HOTSPOTS if h["impact_score"] < 25)
    
    # Aggregate vehicle distribution
    all_vehicles = {}
    for h in HOTSPOTS:
        for vtype, count in h.get("vehicle_distribution", {}).items():
            all_vehicles[vtype] = all_vehicles.get(vtype, 0) + count
    
    return {
        "total_zones": total_zones,
        "total_violations": total_violations,
        "avg_impact_score": round(avg_impact, 1),
        "severity_distribution": {
            "critical": critical,
            "high": high,
            "moderate": moderate,
            "low": low,
        },
        "top_impact_zones": top_impact,
        "top_density_zones": top_density,
        "overlooked_zones": overlooked,
        "police_stations": police_stations,
        "vehicle_distribution": all_vehicles,
    }


@app.get("/api/recommendations")
async def get_recommendations():
    """Get all recommendations, grouped by priority."""
    if not RECOMMENDATIONS:
        raise HTTPException(status_code=404, detail="No recommendations available")
    
    # Group by priority
    grouped = {"Critical": [], "High": [], "Medium": [], "Low": []}
    for rec in RECOMMENDATIONS:
        priority = rec.get("priority", "Low")
        if priority in grouped:
            # Add zone name
            zone_name = "Unknown Zone"
            for h in HOTSPOTS:
                if h["cluster_id"] == rec["zone_id"]:
                    zone_name = h["zone_name"]
                    break
            
            grouped[priority].append({
                **rec,
                "zone_name": zone_name,
            })
    
    return {
        "total": len(RECOMMENDATIONS),
        "by_priority": grouped,
        "all": RECOMMENDATIONS,
    }


@app.post("/api/process")
async def trigger_processing():
    """Trigger the data processing pipeline."""
    try:
        from data_processor import run_pipeline
        clusters, recommendations = run_pipeline()
        load_data()  # Reload the fresh data
        return {
            "status": "success",
            "zones_processed": len(clusters),
            "recommendations_generated": len(recommendations),
        }
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))


if __name__ == "__main__":
    import uvicorn
    uvicorn.run("main:app", host="0.0.0.0", port=8000, reload=True)
